name: "Terraform Deploy"
on:
  push:
    branches:
      - main

# Update secrets TF_VAR_agent_client_id, TF_VAR_agent_client_secret, TF_VAR_subscription_id, TF_VAR_tenant_id in the GitHub repository. 
# For steps to create and store secrets, please check https://docs.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@main

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: "Terraform Format"
        id: fmt
        run: terraform fmt

      - name: "Terraform Init"
        id: init
        run: terraform init

      - name: "Terraform Plan"
        id: plan
        run: terraform plan
        env:
          AZURE_AD_TENANT_ID: ${{secrets.tenantId}}
          AZURE_SUBSCRIPTION_ID: ${{secrets.subscriptionId}}
          AZURE_AD_CLIENT_ID: ${{secrets.clientId}}
          AZURE_AD_CLIENT_SECRET: ${{secrets.clientSecret}}


      - name: "Terraform Apply"
        id: apply
        run: terraform apply -var-file=terraform.tfvars
        env:
          AZURE_AD_TENANT_ID: ${{secrets.tenantId}}
          AZURE_SUBSCRIPTION_ID: ${{secrets.subscriptionId}}
          AZURE_AD_CLIENT_ID: ${{secrets.clientId}}
          AZURE_AD_CLIENT_SECRET: ${{secrets.clientSecret}}
