name: "Terraform Deploy"
on:
  push:
    branches:
      - main

# Update secrets workflows/creating-and-storing-encrypted-secret

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@main

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: "Terraform Format"
        id: fmt
        run: terraform fmt
        working-directory: "./APIManagement"

      - name: "Terraform Init"
        id: init
        run: terraform init
        working-directory: "./APIManagement"
        env:
          ARM_TENANT_ID: ${{secrets.AZURE_AD_TENANT_ID}}
          ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
          ARM_CLIENT_ID: ${{secrets.AZURE_AD_CLIENT_ID}}
          ARM_CLIENT_SECRET: ${{secrets.AZURE_AD_CLIENT_SECRET}}
        
      - name: "Terraform Plan"
        id: plan
        run: |
          terraform plan -out terraform.plan -var-file=terraform.tfvars 
          terraform show -json terraform.plan | tee terraform.json
        working-directory: "./APIManagement"
        env:
          ARM_TENANT_ID: ${{secrets.AZURE_AD_TENANT_ID}}
          ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
          ARM_CLIENT_ID: ${{secrets.AZURE_AD_CLIENT_ID}}
          ARM_CLIENT_SECRET: ${{secrets.AZURE_AD_CLIENT_SECRET}}        


      - name: "Terraform Apply"
        id: apply
        run: terraform apply -var-file=terraform.tfvars -auto-approve
        working-directory: "./APIManagement"
        env:
          ARM_TENANT_ID: ${{secrets.AZURE_AD_TENANT_ID}}
          ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
          ARM_CLIENT_ID: ${{secrets.AZURE_AD_CLIENT_ID}}
          ARM_CLIENT_SECRET: ${{secrets.AZURE_AD_CLIENT_SECRET}}
