location                     = "eastus"
resource_group_name          = "DigiHubRG"
storage_account_name         = "dihasadev"
virtual_network_name         = "diha-vnet"
subnet_name                  = "Core_Subnet"
